### ISSUE TITLE
Barklarm app is not opening

### ISSUE THREAD

**Issue by ezinneanne** [Barklarm/barklarm-app#19]
**Describe the bug**
I downloaded the barklarm app using the Windows Setup .exe link, installed it and after installing, I can see the barklarm logo in my hidden icons but when I click on it, it does not open. 

![Screenshot_135](https://user-images.githubusercontent.com/79814820/203482864-38432d13-05fb-4ef6-b527-b3cb52ad0536.png)

**Comment by kanekotic** [comment]
sorry for the stupid question.  right or left click?, the submenu should apear on right click.

**Comment by ezinneanne** [comment]
> Sorry for the stupid question. Right or left click?, the submenu should appear on left click.

It's working now, I did not know I was supposed to right-click or left-click. I was only clicking on the icon to open then.
![Screenshot_136](https://user-images.githubusercontent.com/79814820/203729148-a767cae9-4fa9-430a-862e-1221fb7ca5c1.png)

**Comment by kanekotic** [comment]
Awesome, I am happy is working. 
I will update the documentation to make this more clear :). Thanks for reporting.
