### ISSUE TITLE
Import all projects from CCTray file

### ISSUE THREAD

**Issue by FabioGNR** [Barklarm/barklarm-app#26]
**Is your feature request related to a problem? Please describe.**
Adding multiple projects all contained in a single CCTray file is cumbersome.

**Describe the solution you'd like**
Dropping a CCTray xml file could prompt with a list of projects contained inside, allowing the user to select/deselect as they wish.
Creating a project for every selected item automatically.

**Describe alternatives you've considered**
Manually copy for each project.

**Additional context**

**Comment by kanekotic** [comment]
Will give it a try, thanks for the request @FabioGNR

**Comment by kanekotic** [comment]
@FabioGNR do you have an example file?

**Comment by FabioGNR** [comment]
Yes, here's an example:

[cc-multiple-projects.txt](https://github.com/Barklarm/barklarm-app/files/12227445/cc-multiple-projects.txt)
It should be a .xml file, but GitHub didn't let me upload it with that extension.
