### ISSUE TITLE
The Barklarm App Improperly Limits In-app Navigation

### ISSUE THREAD

**Issue by masood** [Barklarm/barklarm-app#28]
**Describe the bug**
The Barklarm Desktop Application does not limit in-app navigation. As a result, the application’s window can be navigated to arbitrary third-party sites, resulting in malicious or potentially harmful domains being loaded within the application context.

**To Reproduce**

1. Open the Barklarm Desktop Application from the command-line. Add a command-line switch `--remote-debugging-port=8315` while running the application.

2. Open a web browser on the same device and visit `localhost:8315`. The application can be interacted with via the DevTools protocol.

3. Within the console, update the location, say, `window.location.href = “https://google.com/”. 

4. The Barklarm application window is navigated to `https://google.com/`, i.e., away from the application’s intended page.

**Expected behavior**

The app blocks navigation and prevents the user from navigating to a different domain within the renderer process.

**Desktop (please complete the following information):**
 - OS: Linux

**Credit Information:**

Mir Masood Ali, PhD student, University of Illinois at Chicago
Mohammad Ghasemisharif, PhD Candidate, University of Illinois at Chicago
Chris Kanich, Associate Professor, University of Illinois at Chicago
Jason Polakis, Associate Professor, University of Illinois at Chicago

**Comment by kanekotic** [comment]
Thanks for the report @masood I will have a look at it as soon as I can. Or if you can provide a PR it will be great.
