### ISSUE TITLE
Translations not found on app start

### ISSUE THREAD

**Issue by binair-io** [Barklarm/barklarm-app#48]
**Describe the bug**
After fresh install of Barklarm on Windows 10, get an error:
ENOENT, .vite\assets\translations\en.json not found

**To Reproduce**
1. Install Barklarm using Chocolatey
2. App opens
3. Error is shown

**Expected behavior**
App starts and shows any screen?

**Screenshots**
![afbeelding](https://github.com/user-attachments/assets/e2002f04-098c-466d-b77f-46d70c0d2b1e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: -
 - Version 2.3.1

**Additional context**

**Comment by alvarolorentedev** [comment]
thanks for the issue open @binair-io will check this ASAP

**Comment by confusedsushi** [comment]
FYI, the last working version on Windows is 2.0.0. Beginning with version 2.0.2 the error shows up.
